# Generated by Django 5.0.7 on 2024-08-08 15:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_testing_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='selected_answers',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='selected_answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
