# Generated by Django 5.0.7 on 2024-08-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_testing_service', '0003_useranswer_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='selected_answers',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='selected_answers',
            field=models.ManyToManyField(to='app_testing_service.answer'),
        ),
    ]
